server.port=${PORT:3001}

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

balldontlie.api-key=${BALLDONTLIE_API_KEY}G
balldontlie.base-url=https://api.balldontlie.io

nba.sync.use-fixed-window=${NBA_SYNC_FIXED_WINDOW:false}
nba.sync.window-start=${NBA_SYNC_WINDOW_START:}
nba.sync.window-days=${NBA_SYNC_WINDOW_DAYS:10}

app.frontend-url=${APP_FRONTEND_URL:https://hooppicks.vercel.app}
app.cookie-same-site=None
app.cookie-secure=true